FROM python:3.7-alpine
COPY . /app
WORKDIR /app
RUN apk add --no-cache --virtual .sqlalchemy_deps musl-dev g++
RUN pip install -r r.txt
RUN apk del .sqlalchemy_deps
ENV PYTHONUNBUFFERED=1
ENV FLASK_ENV=development
ENV FLASK_APP=server.py
ENV DB_USERNAME=root
ENV DB_PASSWORD=admin
ENV DB_HOST=mysql-db
ENV DATABASE_NAME=mugo
EXPOSE 5001
ENTRYPOINT ["flask"]
CMD ["run", "--host=0.0.0.0", "--port=5001"]
