import os

FLASK_SECRET_KEY = os.getenv('FLASK_SECRET_KEY', '6$7c8f0e_o9T!z')
FLASK_STATIC_FOLDER = os.getenv('FLASK_STATIC_FOLDER', '../static')
FLASK_UPLOAD_FOLDER = os.getenv('FLASK_UPLOAD_FOLDER', '../static/uploads')
DB_SERVER_HOST = os.getenv('DB_SERVER_HOST', 'localhost')
DB_SERVER_PORT = os.getenv('DB_SERVER_PORT', 5001)
DB_SERVER = f'{DB_SERVER_HOST}:{DB_SERVER_PORT}'
BLOCKCHAIN_SERVER_HOST = os.getenv('BLOCKCHAIN_SERVER_HOST', 'localhost')
BLOCKCHAIN_SERVER_PORT = os.getenv('BLOCKCHAIN_SERVER_PORT', 5000)
BLOCKCHAIN_SERVER = f'{BLOCKCHAIN_SERVER_HOST}:{BLOCKCHAIN_SERVER_PORT}'
