FROM python:3.7-alpine
COPY . /app
WORKDIR /app
RUN pip install flask
ENV PYTHONUNBUFFERED=1
ENV FLASK_ENV=development
ENV FLASK_APP=server.py
EXPOSE 3000
ENTRYPOINT ["flask"]
CMD ["run", "-h 0.0.0.0", "-p 3000"]
